#!/bin/bash

# Make sure at least the command argument is provided.
if [[ $# -lt 1 ]]; then
    echo "Usage: desync <-p|-j> [args...]"
    exit 2
fi

# Execute the appropriate command.
if [[ "$1" = "-p" ]]; then
    $(dirname "$0")/desync-pred "${@:2}"
elif [[ "$1" = "-j" ]]; then
    $(dirname "$0")/desync-junk "${@:2}"
else
    echo "Unknown command flag \"$1\"."
    exit 2
fi
